
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi.practica_1_compi.parser;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
 */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

    public final Class getSymbolContainer() {
        return sym.class;
    }

    /** Default constructor. */
    @Deprecated
    public parser() {super();}

    /** Constructor which sets the default scanner. */
    @Deprecated
    public parser(java_cup.runtime.Scanner s) {super(s);}

    /** Constructor which sets the default scanner. */
    public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

    /** Production table. */
    protected static final short _production_table[][] =
            unpackFromStrings(new String[] {
                    "\000\061\000\002\002\005\000\002\002\004\000\002\002" +
                            "\003\000\002\003\005\000\002\004\004\000\002\004\003" +
                            "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
                            "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
                            "\007\004\000\002\007\006\000\002\006\005\000\002\010" +
                            "\004\000\002\010\004\000\002\011\004\000\002\012\011" +
                            "\000\002\013\011\000\002\014\005\000\002\014\005\000" +
                            "\002\014\003\000\002\015\005\000\002\015\005\000\002" +
                            "\015\003\000\002\016\003\000\002\016\003\000\002\016" +
                            "\003\000\002\016\005\000\002\017\003\000\002\020\004" +
                            "\000\002\020\003\000\002\021\005\000\002\021\007\000" +
                            "\002\021\007\000\002\021\007\000\002\021\007\000\002" +
                            "\021\007\000\002\021\007\000\002\021\007\000\002\021" +
                            "\007\000\002\021\007\000\002\021\007\000\002\021\007" +
                            "\000\002\021\007\000\002\021\007\000\002\021\007\000" +
                            "\002\021\007" });

    /** Access to production table. */
    public short[][] production_table() {return _production_table;}

    /** Parse-action table. */
    protected static final short[][] _action_table =
            unpackFromStrings(new String[] {
                    "\000\214\000\004\004\004\001\002\000\016\006\160\007" +
                            "\167\012\166\015\154\016\161\074\164\001\002\000\004" +
                            "\002\152\001\002\000\006\002\uffff\037\007\001\002\000" +
                            "\042\042\027\043\022\044\026\045\020\046\012\047\010" +
                            "\050\025\051\017\052\024\053\023\054\015\055\011\056" +
                            "\016\057\032\060\013\061\021\001\002\000\004\034\146" +
                            "\001\002\000\004\034\142\001\002\000\004\034\136\001" +
                            "\002\000\004\034\132\001\002\000\044\002\uffe3\042\027" +
                            "\043\022\044\026\045\020\046\012\047\010\050\025\051" +
                            "\017\052\024\053\023\054\015\055\011\056\016\057\032" +
                            "\060\013\061\021\001\002\000\004\034\125\001\002\000" +
                            "\004\034\121\001\002\000\004\034\115\001\002\000\004" +
                            "\034\111\001\002\000\004\034\105\001\002\000\004\034" +
                            "\101\001\002\000\004\034\075\001\002\000\004\034\071" +
                            "\001\002\000\004\034\065\001\002\000\004\034\041\001" +
                            "\002\000\004\034\037\001\002\000\044\002\uffe1\042\uffe1" +
                            "\043\uffe1\044\uffe1\045\uffe1\046\uffe1\047\uffe1\050\uffe1\051" +
                            "\uffe1\052\uffe1\053\uffe1\054\uffe1\055\uffe1\056\uffe1\057\uffe1" +
                            "\060\uffe1\061\uffe1\001\002\000\004\002\001\001\002\000" +
                            "\004\034\033\001\002\000\004\074\034\001\002\000\004" +
                            "\040\035\001\002\000\004\075\036\001\002\000\044\002" +
                            "\uffd3\042\uffd3\043\uffd3\044\uffd3\045\uffd3\046\uffd3\047\uffd3" +
                            "\050\uffd3\051\uffd3\052\uffd3\053\uffd3\054\uffd3\055\uffd3\056" +
                            "\uffd3\057\uffd3\060\uffd3\061\uffd3\001\002\000\004\075\040" +
                            "\001\002\000\044\002\uffe0\042\uffe0\043\uffe0\044\uffe0\045" +
                            "\uffe0\046\uffe0\047\uffe0\050\uffe0\051\uffe0\052\uffe0\053\uffe0" +
                            "\054\uffe0\055\uffe0\056\uffe0\057\uffe0\060\uffe0\061\uffe0\001" +
                            "\002\000\012\035\044\074\042\075\046\076\045\001\002" +
                            "\000\040\005\uffe5\006\uffe5\007\uffe5\011\uffe5\012\uffe5\014" +
                            "\uffe5\015\uffe5\016\uffe5\017\uffe5\020\uffe5\021\uffe5\022\uffe5" +
                            "\036\uffe5\040\uffe5\074\uffe5\001\002\000\040\005\uffe8\006" +
                            "\uffe8\007\uffe8\011\uffe8\012\uffe8\014\uffe8\015\uffe8\016\uffe8" +
                            "\017\uffe8\020\uffe8\021\uffe8\022\uffe8\036\uffe8\040\uffe8\074" +
                            "\uffe8\001\002\000\012\035\044\074\042\075\046\076\045" +
                            "\001\002\000\040\005\uffe6\006\uffe6\007\uffe6\011\uffe6\012" +
                            "\uffe6\014\uffe6\015\uffe6\016\uffe6\017\uffe6\020\uffe6\021\uffe6" +
                            "\022\uffe6\036\uffe6\040\uffe6\074\uffe6\001\002\000\040\005" +
                            "\uffe7\006\uffe7\007\uffe7\011\uffe7\012\uffe7\014\uffe7\015\uffe7" +
                            "\016\uffe7\017\uffe7\020\uffe7\021\uffe7\022\uffe7\036\uffe7\040" +
                            "\uffe7\074\uffe7\001\002\000\040\005\uffeb\006\uffeb\007\uffeb" +
                            "\011\uffeb\012\uffeb\014\uffeb\015\uffeb\016\uffeb\017\uffeb\020" +
                            "\uffeb\021\056\022\055\036\uffeb\040\uffeb\074\uffeb\001\002" +
                            "\000\010\017\051\020\053\040\052\001\002\000\012\035" +
                            "\044\074\042\075\046\076\045\001\002\000\004\075\061" +
                            "\001\002\000\012\035\044\074\042\075\046\076\045\001" +
                            "\002\000\040\005\uffec\006\uffec\007\uffec\011\uffec\012\uffec" +
                            "\014\uffec\015\uffec\016\uffec\017\uffec\020\uffec\021\056\022" +
                            "\055\036\uffec\040\uffec\074\uffec\001\002\000\012\035\044" +
                            "\074\042\075\046\076\045\001\002\000\012\035\044\074" +
                            "\042\075\046\076\045\001\002\000\040\005\uffea\006\uffea" +
                            "\007\uffea\011\uffea\012\uffea\014\uffea\015\uffea\016\uffea\017" +
                            "\uffea\020\uffea\021\uffea\022\uffea\036\uffea\040\uffea\074\uffea" +
                            "\001\002\000\040\005\uffe9\006\uffe9\007\uffe9\011\uffe9\012" +
                            "\uffe9\014\uffe9\015\uffe9\016\uffe9\017\uffe9\020\uffe9\021\uffe9" +
                            "\022\uffe9\036\uffe9\040\uffe9\074\uffe9\001\002\000\044\002" +
                            "\uffde\042\uffde\043\uffde\044\uffde\045\uffde\046\uffde\047\uffde" +
                            "\050\uffde\051\uffde\052\uffde\053\uffde\054\uffde\055\uffde\056" +
                            "\uffde\057\uffde\060\uffde\061\uffde\001\002\000\040\005\uffed" +
                            "\006\uffed\007\uffed\011\uffed\012\uffed\014\uffed\015\uffed\016" +
                            "\uffed\017\uffed\020\uffed\021\056\022\055\036\uffed\040\uffed" +
                            "\074\uffed\001\002\000\010\017\051\020\053\036\064\001" +
                            "\002\000\040\005\uffe4\006\uffe4\007\uffe4\011\uffe4\012\uffe4" +
                            "\014\uffe4\015\uffe4\016\uffe4\017\uffe4\020\uffe4\021\uffe4\022" +
                            "\uffe4\036\uffe4\040\uffe4\074\uffe4\001\002\000\012\035\044" +
                            "\074\042\075\046\076\045\001\002\000\010\017\051\020" +
                            "\053\040\067\001\002\000\004\075\070\001\002\000\044" +
                            "\002\uffda\042\uffda\043\uffda\044\uffda\045\uffda\046\uffda\047" +
                            "\uffda\050\uffda\051\uffda\052\uffda\053\uffda\054\uffda\055\uffda" +
                            "\056\uffda\057\uffda\060\uffda\061\uffda\001\002\000\004\074" +
                            "\072\001\002\000\004\040\073\001\002\000\004\075\074" +
                            "\001\002\000\044\002\uffd8\042\uffd8\043\uffd8\044\uffd8\045" +
                            "\uffd8\046\uffd8\047\uffd8\050\uffd8\051\uffd8\052\uffd8\053\uffd8" +
                            "\054\uffd8\055\uffd8\056\uffd8\057\uffd8\060\uffd8\061\uffd8\001" +
                            "\002\000\004\074\076\001\002\000\004\040\077\001\002" +
                            "\000\004\075\100\001\002\000\044\002\uffd7\042\uffd7\043" +
                            "\uffd7\044\uffd7\045\uffd7\046\uffd7\047\uffd7\050\uffd7\051\uffd7" +
                            "\052\uffd7\053\uffd7\054\uffd7\055\uffd7\056\uffd7\057\uffd7\060" +
                            "\uffd7\061\uffd7\001\002\000\012\035\044\074\042\075\046" +
                            "\076\045\001\002\000\010\017\051\020\053\040\103\001" +
                            "\002\000\004\075\104\001\002\000\044\002\uffdf\042\uffdf" +
                            "\043\uffdf\044\uffdf\045\uffdf\046\uffdf\047\uffdf\050\uffdf\051" +
                            "\uffdf\052\uffdf\053\uffdf\054\uffdf\055\uffdf\056\uffdf\057\uffdf" +
                            "\060\uffdf\061\uffdf\001\002\000\012\035\044\074\042\075" +
                            "\046\076\045\001\002\000\010\017\051\020\053\040\107" +
                            "\001\002\000\004\075\110\001\002\000\044\002\uffd1\042" +
                            "\uffd1\043\uffd1\044\uffd1\045\uffd1\046\uffd1\047\uffd1\050\uffd1" +
                            "\051\uffd1\052\uffd1\053\uffd1\054\uffd1\055\uffd1\056\uffd1\057" +
                            "\uffd1\060\uffd1\061\uffd1\001\002\000\004\074\112\001\002" +
                            "\000\004\040\113\001\002\000\004\075\114\001\002\000" +
                            "\044\002\uffdd\042\uffdd\043\uffdd\044\uffdd\045\uffdd\046\uffdd" +
                            "\047\uffdd\050\uffdd\051\uffdd\052\uffdd\053\uffdd\054\uffdd\055" +
                            "\uffdd\056\uffdd\057\uffdd\060\uffdd\061\uffdd\001\002\000\012" +
                            "\035\044\074\042\075\046\076\045\001\002\000\010\017" +
                            "\051\020\053\040\117\001\002\000\004\075\120\001\002" +
                            "\000\044\002\uffd9\042\uffd9\043\uffd9\044\uffd9\045\uffd9\046" +
                            "\uffd9\047\uffd9\050\uffd9\051\uffd9\052\uffd9\053\uffd9\054\uffd9" +
                            "\055\uffd9\056\uffd9\057\uffd9\060\uffd9\061\uffd9\001\002\000" +
                            "\012\035\044\074\042\075\046\076\045\001\002\000\010" +
                            "\017\051\020\053\040\123\001\002\000\004\075\124\001" +
                            "\002\000\044\002\uffd4\042\uffd4\043\uffd4\044\uffd4\045\uffd4" +
                            "\046\uffd4\047\uffd4\050\uffd4\051\uffd4\052\uffd4\053\uffd4\054" +
                            "\uffd4\055\uffd4\056\uffd4\057\uffd4\060\uffd4\061\uffd4\001\002" +
                            "\000\012\035\044\074\042\075\046\076\045\001\002\000" +
                            "\010\017\051\020\053\040\127\001\002\000\004\075\130" +
                            "\001\002\000\044\002\uffd6\042\uffd6\043\uffd6\044\uffd6\045" +
                            "\uffd6\046\uffd6\047\uffd6\050\uffd6\051\uffd6\052\uffd6\053\uffd6" +
                            "\054\uffd6\055\uffd6\056\uffd6\057\uffd6\060\uffd6\061\uffd6\001" +
                            "\002\000\044\002\uffe2\042\uffe2\043\uffe2\044\uffe2\045\uffe2" +
                            "\046\uffe2\047\uffe2\050\uffe2\051\uffe2\052\uffe2\053\uffe2\054" +
                            "\uffe2\055\uffe2\056\uffe2\057\uffe2\060\uffe2\061\uffe2\001\002" +
                            "\000\004\074\133\001\002\000\004\040\134\001\002\000" +
                            "\004\075\135\001\002\000\044\002\uffd2\042\uffd2\043\uffd2" +
                            "\044\uffd2\045\uffd2\046\uffd2\047\uffd2\050\uffd2\051\uffd2\052" +
                            "\uffd2\053\uffd2\054\uffd2\055\uffd2\056\uffd2\057\uffd2\060\uffd2" +
                            "\061\uffd2\001\002\000\004\074\137\001\002\000\004\040" +
                            "\140\001\002\000\004\075\141\001\002\000\044\002\uffdc" +
                            "\042\uffdc\043\uffdc\044\uffdc\045\uffdc\046\uffdc\047\uffdc\050" +
                            "\uffdc\051\uffdc\052\uffdc\053\uffdc\054\uffdc\055\uffdc\056\uffdc" +
                            "\057\uffdc\060\uffdc\061\uffdc\001\002\000\012\035\044\074" +
                            "\042\075\046\076\045\001\002\000\010\017\051\020\053" +
                            "\040\144\001\002\000\004\075\145\001\002\000\044\002" +
                            "\uffd5\042\uffd5\043\uffd5\044\uffd5\045\uffd5\046\uffd5\047\uffd5" +
                            "\050\uffd5\051\uffd5\052\uffd5\053\uffd5\054\uffd5\055\uffd5\056" +
                            "\uffd5\057\uffd5\060\uffd5\061\uffd5\001\002\000\012\035\044" +
                            "\074\042\075\046\076\045\001\002\000\010\017\051\020" +
                            "\053\040\150\001\002\000\004\075\151\001\002\000\044" +
                            "\002\uffdb\042\uffdb\043\uffdb\044\uffdb\045\uffdb\046\uffdb\047" +
                            "\uffdb\050\uffdb\051\uffdb\052\uffdb\053\uffdb\054\uffdb\055\uffdb" +
                            "\056\uffdb\057\uffdb\060\uffdb\061\uffdb\001\002\000\004\002" +
                            "\000\001\002\000\020\005\216\006\160\007\167\012\166" +
                            "\015\154\016\161\074\164\001\002\000\006\074\214\077" +
                            "\215\001\002\000\024\005\ufff7\006\ufff7\007\ufff7\011\ufff7" +
                            "\012\ufff7\014\ufff7\015\ufff7\016\ufff7\074\ufff7\001\002\000" +
                            "\024\005\ufffc\006\ufffc\007\ufffc\011\ufffc\012\ufffc\014\ufffc" +
                            "\015\ufffc\016\ufffc\074\ufffc\001\002\000\024\005\ufffa\006" +
                            "\ufffa\007\ufffa\011\ufffa\012\ufffa\014\ufffa\015\ufffa\016\ufffa" +
                            "\074\ufffa\001\002\000\004\074\211\001\002\000\004\074" +
                            "\210\001\002\000\024\005\ufffb\006\ufffb\007\ufffb\011\ufffb" +
                            "\012\ufffb\014\ufffb\015\ufffb\016\ufffb\074\ufffb\001\002\000" +
                            "\024\005\ufff6\006\ufff6\007\ufff6\011\ufff6\012\ufff6\014\ufff6" +
                            "\015\ufff6\016\ufff6\074\ufff6\001\002\000\004\034\206\001" +
                            "\002\000\024\005\ufff8\006\ufff8\007\ufff8\011\ufff8\012\ufff8" +
                            "\014\ufff8\015\ufff8\016\ufff8\074\ufff8\001\002\000\004\035" +
                            "\200\001\002\000\004\035\171\001\002\000\024\005\ufff9" +
                            "\006\ufff9\007\ufff9\011\ufff9\012\ufff9\014\ufff9\015\ufff9\016" +
                            "\ufff9\074\ufff9\001\002\000\012\035\044\074\042\075\046" +
                            "\076\045\001\002\000\010\017\051\020\053\036\173\001" +
                            "\002\000\004\010\174\001\002\000\016\006\160\007\167" +
                            "\012\166\015\154\016\161\074\164\001\002\000\020\006" +
                            "\160\007\167\011\177\012\166\015\154\016\161\074\164" +
                            "\001\002\000\024\005\ufffd\006\ufffd\007\ufffd\011\ufffd\012" +
                            "\ufffd\014\ufffd\015\ufffd\016\ufffd\074\ufffd\001\002\000\024" +
                            "\005\uffef\006\uffef\007\uffef\011\uffef\012\uffef\014\uffef\015" +
                            "\uffef\016\uffef\074\uffef\001\002\000\012\035\044\074\042" +
                            "\075\046\076\045\001\002\000\010\017\051\020\053\036" +
                            "\202\001\002\000\004\013\203\001\002\000\016\006\160" +
                            "\007\167\012\166\015\154\016\161\074\164\001\002\000" +
                            "\020\006\160\007\167\012\166\014\205\015\154\016\161" +
                            "\074\164\001\002\000\024\005\uffee\006\uffee\007\uffee\011" +
                            "\uffee\012\uffee\014\uffee\015\uffee\016\uffee\074\uffee\001\002" +
                            "\000\012\035\044\074\042\075\046\076\045\001\002\000" +
                            "\030\005\ufff3\006\ufff3\007\ufff3\011\ufff3\012\ufff3\014\ufff3" +
                            "\015\ufff3\016\ufff3\017\051\020\053\074\ufff3\001\002\000" +
                            "\024\005\ufff0\006\ufff0\007\ufff0\011\ufff0\012\ufff0\014\ufff0" +
                            "\015\ufff0\016\ufff0\074\ufff0\001\002\000\026\005\ufff5\006" +
                            "\ufff5\007\ufff5\011\ufff5\012\ufff5\014\ufff5\015\ufff5\016\ufff5" +
                            "\034\212\074\ufff5\001\002\000\012\035\044\074\042\075" +
                            "\046\076\045\001\002\000\030\005\ufff4\006\ufff4\007\ufff4" +
                            "\011\ufff4\012\ufff4\014\ufff4\015\ufff4\016\ufff4\017\051\020" +
                            "\053\074\ufff4\001\002\000\024\005\ufff1\006\ufff1\007\ufff1" +
                            "\011\ufff1\012\ufff1\014\ufff1\015\ufff1\016\ufff1\074\ufff1\001" +
                            "\002\000\024\005\ufff2\006\ufff2\007\ufff2\011\ufff2\012\ufff2" +
                            "\014\ufff2\015\ufff2\016\ufff2\074\ufff2\001\002\000\006\002" +
                            "\ufffe\037\ufffe\001\002" });

    /** Access to parse-action table. */
    public short[][] action_table() {return _action_table;}

    /** <code>reduce_goto</code> table. */
    protected static final short[][] _reduce_table =
            unpackFromStrings(new String[] {
                    "\000\214\000\006\002\004\003\005\001\001\000\022\004" +
                            "\152\005\155\006\156\007\161\010\167\011\164\012\154" +
                            "\013\162\001\001\000\002\001\001\000\002\001\001\000" +
                            "\010\017\030\020\013\021\027\001\001\000\002\001\001" +
                            "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                            "\004\021\130\001\001\000\002\001\001\000\002\001\001" +
                            "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                            "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
                            "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                            "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                            "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                            "\002\001\001\000\002\001\001\000\010\014\047\015\046" +
                            "\016\042\001\001\000\002\001\001\000\002\001\001\000" +
                            "\010\014\062\015\046\016\042\001\001\000\002\001\001" +
                            "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                            "\006\015\061\016\042\001\001\000\002\001\001\000\006" +
                            "\015\053\016\042\001\001\000\002\001\001\000\004\016" +
                            "\057\001\001\000\004\016\056\001\001\000\002\001\001" +
                            "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                            "\002\001\001\000\002\001\001\000\010\014\065\015\046" +
                            "\016\042\001\001\000\002\001\001\000\002\001\001\000" +
                            "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
                            "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                            "\001\000\002\001\001\000\002\001\001\000\010\014\101" +
                            "\015\046\016\042\001\001\000\002\001\001\000\002\001" +
                            "\001\000\002\001\001\000\010\014\105\015\046\016\042" +
                            "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                            "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                            "\000\002\001\001\000\010\014\115\015\046\016\042\001" +
                            "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                            "\000\010\014\121\015\046\016\042\001\001\000\002\001" +
                            "\001\000\002\001\001\000\002\001\001\000\010\014\125" +
                            "\015\046\016\042\001\001\000\002\001\001\000\002\001" +
                            "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                            "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                            "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
                            "\001\001\000\010\014\142\015\046\016\042\001\001\000" +
                            "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
                            "\014\146\015\046\016\042\001\001\000\002\001\001\000" +
                            "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
                            "\005\175\006\156\007\161\010\167\011\164\012\154\013" +
                            "\162\001\001\000\002\001\001\000\002\001\001\000\002" +
                            "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                            "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                            "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                            "\002\001\001\000\010\014\171\015\046\016\042\001\001" +
                            "\000\002\001\001\000\002\001\001\000\022\004\174\005" +
                            "\155\006\156\007\161\010\167\011\164\012\154\013\162" +
                            "\001\001\000\020\005\175\006\156\007\161\010\167\011" +
                            "\164\012\154\013\162\001\001\000\002\001\001\000\002" +
                            "\001\001\000\010\014\200\015\046\016\042\001\001\000" +
                            "\002\001\001\000\002\001\001\000\022\004\203\005\155" +
                            "\006\156\007\161\010\167\011\164\012\154\013\162\001" +
                            "\001\000\020\005\175\006\156\007\161\010\167\011\164" +
                            "\012\154\013\162\001\001\000\002\001\001\000\010\014" +
                            "\206\015\046\016\042\001\001\000\002\001\001\000\002" +
                            "\001\001\000\002\001\001\000\010\014\212\015\046\016" +
                            "\042\001\001\000\002\001\001\000\002\001\001\000\002" +
                            "\001\001\000\002\001\001" });

    /** Access to <code>reduce_goto</code> table. */
    public short[][] reduce_table() {return _reduce_table;}

    /** Instance of action encapsulation class. */
    protected CUP$parser$actions action_obj;

    /** Action encapsulation object initializer. */
    protected void init_actions()
    {
        action_obj = new CUP$parser$actions(this);
    }

    /** Invoke a user supplied parse action. */
    public java_cup.runtime.Symbol do_action(
            int                        act_num,
            java_cup.runtime.lr_parser parser,
            java.util.Stack            stack,
            int                        top)
            throws java.lang.Exception
    {
        /* call code in generated class */
        return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
    }

    /** Indicates start state. */
    public int start_state() {return 0;}
    /** Indicates start production. */
    public int start_production() {return 1;}

    /** <code>EOF</code> Symbol index. */
    public int EOF_sym() {return 0;}

    /** <code>error</code> Symbol index. */
    public int error_sym() {return 1;}



    private java.util.List<String> syntaxErrors = new java.util.ArrayList<>();

    public java.util.List<String> getSyntaxErrors() {
        return syntaxErrors;
    }

    @Override
    public void report_error(String message, Object info) {
        if (info instanceof java_cup.runtime.Symbol s) {
            syntaxErrors.add(
                    "Sintáctico -> Línea: " + s.left +
                            " Columna: " + s.right +
                            " " + message
            );
        } else {
            syntaxErrors.add("Sintáctico -> " + message);
        }
    }

    @Override
    public void report_fatal_error(String message, Object info) throws Exception {
        if (info instanceof java_cup.runtime.Symbol s) {
            syntaxErrors.add(
                    "Fatal -> Línea: " + s.left +
                            " Columna: " + s.right +
                            " " + message
            );
        } else {
            syntaxErrors.add("Fatal -> " + message);
        }
        super.report_fatal_error(message, info);
    }
}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
    private final parser parser;

    /** Constructor */
    CUP$parser$actions(parser parser) {
        this.parser = parser;
    }

    /** Method 0 with the actual generated action code for actions 0 to 300. */
    public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack            CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception
    {
        /* Symbol object for return from actions */
        java_cup.runtime.Symbol CUP$parser$result;

        /* select the action based on the action number */
        switch (CUP$parser$act_num)
        {
            /*. . . . . . . . . . . . . . . . . . . .*/
            case 0: // inicio ::= algoritmo SEPARADOR configuracion
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 1: // $START ::= inicio EOF
            {
                Object RESULT =null;
                int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
                int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
                Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
                RESULT = start_val;
                CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            /* ACCEPT */
            CUP$parser$parser.done_parsing();
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 2: // inicio ::= algoritmo
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 3: // algoritmo ::= INICIO bloque FIN
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("algoritmo",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 4: // bloque ::= bloque instruccion
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 5: // bloque ::= instruccion
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 6: // instruccion ::= declaracion
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 7: // instruccion ::= asignacion
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 8: // instruccion ::= mostrar
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 9: // instruccion ::= leer
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 10: // instruccion ::= si
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 11: // instruccion ::= mientras
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 12: // declaracion ::= VAR ID
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 13: // declaracion ::= VAR ID ASIGNACION expresion
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 14: // asignacion ::= ID ASIGNACION expresion
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("asignacion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 15: // mostrar ::= MOSTRAR CADENA
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 16: // mostrar ::= MOSTRAR ID
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 17: // leer ::= LEER ID
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("leer",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 18: // si ::= SI PAREN_IZQ expresion PAREN_DER ENTONCES bloque FINSI
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("si",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 19: // mientras ::= MIENTRAS PAREN_IZQ expresion PAREN_DER HACER bloque FINMIENTRAS
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("mientras",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 20: // expresion ::= expresion MAS termino
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 21: // expresion ::= expresion MENOS termino
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 22: // expresion ::= termino
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 23: // termino ::= termino POR factor
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 24: // termino ::= termino DIV factor
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 25: // termino ::= factor
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 26: // factor ::= ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 27: // factor ::= DECIMAL
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 28: // factor ::= ID
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 29: // factor ::= PAREN_IZQ expresion PAREN_DER
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 30: // configuracion ::= lista_config
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("configuracion",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 31: // lista_config ::= lista_config config
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_config",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 32: // lista_config ::= config
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_config",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 33: // config ::= DEFAULT ASIGNACION ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 34: // config ::= COLOR_TEXTO_SI ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 35: // config ::= COLOR_SI ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 36: // config ::= FIGURA_SI ASIGNACION ID BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 37: // config ::= LETRA_SI ASIGNACION ID BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 38: // config ::= LETRA_SIZE_SI ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 39: // config ::= COLOR_TEXTO_MIENTRAS ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 40: // config ::= COLOR_MIENTRAS ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 41: // config ::= FIGURA_MIENTRAS ASIGNACION ID BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 42: // config ::= LETRA_MIENTRAS ASIGNACION ID BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 43: // config ::= LETRA_SIZE_MIENTRAS ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 44: // config ::= COLOR_TEXTO_BLOQUE ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 45: // config ::= COLOR_BLOQUE ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 46: // config ::= FIGURA_BLOQUE ASIGNACION ID BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 47: // config ::= LETRA_BLOQUE ASIGNACION ID BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /*. . . . . . . . . . . . . . . . . . . .*/
            case 48: // config ::= LETRA_SIZE_BLOQUE ASIGNACION expresion BARRA ENTERO
            {
                Object RESULT =null;

                CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
            return CUP$parser$result;

            /* . . . . . .*/
            default:
                throw new Exception(
                        "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

    /** Method splitting the generated action code into several parts. */
    public final java_cup.runtime.Symbol CUP$parser$do_action(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack            CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception
    {
        return CUP$parser$do_action_part00000000(
                CUP$parser$act_num,
                CUP$parser$parser,
                CUP$parser$stack,
                CUP$parser$top);
    }
}