
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi.practica_1_compi.parser;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
 */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

  public final Class getSymbolContainer() {
    return sym.class;
  }

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] =
          unpackFromStrings(new String[] {
                  "\000\110\000\002\002\005\000\002\002\004\000\002\002" +
                          "\003\000\002\003\005\000\002\004\004\000\002\004\003" +
                          "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
                          "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
                          "\007\004\000\002\007\006\000\002\006\005\000\002\010" +
                          "\004\000\002\010\004\000\002\011\004\000\002\012\011" +
                          "\000\002\013\011\000\002\014\005\000\002\014\005\000" +
                          "\002\014\005\000\002\014\005\000\002\014\005\000\002" +
                          "\014\005\000\002\014\005\000\002\014\005\000\002\014" +
                          "\005\000\002\014\005\000\002\014\004\000\002\014\003" +
                          "\000\002\015\005\000\002\015\005\000\002\015\003\000" +
                          "\002\016\003\000\002\016\003\000\002\016\003\000\002" +
                          "\016\005\000\002\017\003\000\002\020\004\000\002\020" +
                          "\003\000\002\021\005\000\002\021\007\000\002\021\007" +
                          "\000\002\021\007\000\002\021\007\000\002\021\007\000" +
                          "\002\021\007\000\002\021\007\000\002\021\007\000\002" +
                          "\021\007\000\002\021\007\000\002\021\007\000\002\021" +
                          "\007\000\002\021\007\000\002\021\007\000\002\021\007" +
                          "\000\002\024\003\000\002\024\007\000\002\022\003\000" +
                          "\002\022\003\000\002\022\003\000\002\022\003\000\002" +
                          "\022\003\000\002\022\003\000\002\022\003\000\002\023" +
                          "\003\000\002\023\003\000\002\023\003\000\002\023\003" +
                          "\000\002\023\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table =
          unpackFromStrings(new String[] {
                  "\000\257\000\004\004\004\001\002\000\016\006\223\007" +
                          "\232\012\231\015\217\016\224\074\227\001\002\000\004" +
                          "\002\215\001\002\000\006\002\uffff\037\007\001\002\000" +
                          "\042\042\027\043\022\044\026\045\020\046\012\047\010" +
                          "\050\024\051\017\052\025\053\023\054\015\055\011\056" +
                          "\016\057\032\060\013\061\021\001\002\000\004\034\211" +
                          "\001\002\000\004\034\205\001\002\000\004\034\201\001" +
                          "\002\000\004\034\175\001\002\000\044\002\uffda\042\027" +
                          "\043\022\044\026\045\020\046\012\047\010\050\024\051" +
                          "\017\052\025\053\023\054\015\055\011\056\016\057\032" +
                          "\060\013\061\021\001\002\000\004\034\170\001\002\000" +
                          "\004\034\164\001\002\000\004\034\160\001\002\000\004" +
                          "\034\154\001\002\000\004\034\150\001\002\000\004\034" +
                          "\144\001\002\000\004\034\133\001\002\000\004\034\127" +
                          "\001\002\000\004\034\123\001\002\000\004\034\050\001" +
                          "\002\000\004\034\046\001\002\000\044\002\uffd8\042\uffd8" +
                          "\043\uffd8\044\uffd8\045\uffd8\046\uffd8\047\uffd8\050\uffd8\051" +
                          "\uffd8\052\uffd8\053\uffd8\054\uffd8\055\uffd8\056\uffd8\057\uffd8" +
                          "\060\uffd8\061\uffd8\001\002\000\004\002\001\001\002\000" +
                          "\004\034\033\001\002\000\020\062\042\063\041\064\040" +
                          "\065\035\066\043\067\037\074\034\001\002\000\004\040" +
                          "\uffc5\001\002\000\004\040\uffc1\001\002\000\004\040\044" +
                          "\001\002\000\004\040\uffbf\001\002\000\004\040\uffc2\001" +
                          "\002\000\004\040\uffc3\001\002\000\004\040\uffc4\001\002" +
                          "\000\004\040\uffc0\001\002\000\004\075\045\001\002\000" +
                          "\044\002\uffca\042\uffca\043\uffca\044\uffca\045\uffca\046\uffca" +
                          "\047\uffca\050\uffca\051\uffca\052\uffca\053\uffca\054\uffca\055" +
                          "\uffca\056\uffca\057\uffca\060\uffca\061\uffca\001\002\000\004" +
                          "\075\047\001\002\000\044\002\uffd7\042\uffd7\043\uffd7\044" +
                          "\uffd7\045\uffd7\046\uffd7\047\uffd7\050\uffd7\051\uffd7\052\uffd7" +
                          "\053\uffd7\054\uffd7\055\uffd7\056\uffd7\057\uffd7\060\uffd7\061" +
                          "\uffd7\001\002\000\014\033\061\035\052\074\056\075\053" +
                          "\076\051\001\002\000\062\005\uffdd\006\uffdd\007\uffdd\011" +
                          "\uffdd\012\uffdd\014\uffdd\015\uffdd\016\uffdd\017\uffdd\020\uffdd" +
                          "\021\uffdd\022\uffdd\023\uffdd\024\uffdd\025\uffdd\026\uffdd\027" +
                          "\uffdd\030\uffdd\031\uffdd\032\uffdd\036\uffdd\040\uffdd\041\uffdd" +
                          "\074\uffdd\001\002\000\014\033\061\035\052\074\056\075" +
                          "\053\076\051\001\002\000\062\005\uffde\006\uffde\007\uffde" +
                          "\011\uffde\012\uffde\014\uffde\015\uffde\016\uffde\017\uffde\020" +
                          "\uffde\021\uffde\022\uffde\023\uffde\024\uffde\025\uffde\026\uffde" +
                          "\027\uffde\030\uffde\031\uffde\032\uffde\036\uffde\040\uffde\041" +
                          "\uffde\074\uffde\001\002\000\062\005\uffe2\006\uffe2\007\uffe2" +
                          "\011\uffe2\012\uffe2\014\uffe2\015\uffe2\016\uffe2\017\uffe2\020" +
                          "\uffe2\021\077\022\076\023\uffe2\024\uffe2\025\uffe2\026\uffe2" +
                          "\027\uffe2\030\uffe2\031\uffe2\032\uffe2\036\uffe2\040\uffe2\041" +
                          "\uffe2\074\uffe2\001\002\000\032\017\067\020\064\023\071" +
                          "\024\072\025\070\026\065\027\066\030\074\031\063\032" +
                          "\073\040\uffc7\041\115\001\002\000\062\005\uffdc\006\uffdc" +
                          "\007\uffdc\011\uffdc\012\uffdc\014\uffdc\015\uffdc\016\uffdc\017" +
                          "\uffdc\020\uffdc\021\uffdc\022\uffdc\023\uffdc\024\uffdc\025\uffdc" +
                          "\026\uffdc\027\uffdc\030\uffdc\031\uffdc\032\uffdc\036\uffdc\040" +
                          "\uffdc\041\uffdc\074\uffdc\001\002\000\062\005\uffdf\006\uffdf" +
                          "\007\uffdf\011\uffdf\012\uffdf\014\uffdf\015\uffdf\016\uffdf\017" +
                          "\uffdf\020\uffdf\021\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf" +
                          "\026\uffdf\027\uffdf\030\uffdf\031\uffdf\032\uffdf\036\uffdf\040" +
                          "\uffdf\041\uffdf\074\uffdf\001\002\000\004\040\113\001\002" +
                          "\000\014\033\061\035\052\074\056\075\053\076\051\001" +
                          "\002\000\056\005\uffe3\006\uffe3\007\uffe3\011\uffe3\012\uffe3" +
                          "\014\uffe3\015\uffe3\016\uffe3\017\067\020\064\023\071\024" +
                          "\072\025\070\026\065\027\066\030\074\031\uffe3\032\uffe3" +
                          "\036\uffe3\040\uffe3\041\uffe3\074\uffe3\001\002\000\014\033" +
                          "\061\035\052\074\056\075\053\076\051\001\002\000\012" +
                          "\035\052\074\056\075\053\076\051\001\002\000\012\035" +
                          "\052\074\056\075\053\076\051\001\002\000\012\035\052" +
                          "\074\056\075\053\076\051\001\002\000\012\035\052\074" +
                          "\056\075\053\076\051\001\002\000\012\035\052\074\056" +
                          "\075\053\076\051\001\002\000\012\035\052\074\056\075" +
                          "\053\076\051\001\002\000\012\035\052\074\056\075\053" +
                          "\076\051\001\002\000\014\033\061\035\052\074\056\075" +
                          "\053\076\051\001\002\000\012\035\052\074\056\075\053" +
                          "\076\051\001\002\000\062\005\uffe6\006\uffe6\007\uffe6\011" +
                          "\uffe6\012\uffe6\014\uffe6\015\uffe6\016\uffe6\017\uffe6\020\uffe6" +
                          "\021\077\022\076\023\uffe6\024\uffe6\025\uffe6\026\uffe6\027" +
                          "\uffe6\030\uffe6\031\uffe6\032\uffe6\036\uffe6\040\uffe6\041\uffe6" +
                          "\074\uffe6\001\002\000\012\035\052\074\056\075\053\076" +
                          "\051\001\002\000\012\035\052\074\056\075\053\076\051" +
                          "\001\002\000\062\005\uffe1\006\uffe1\007\uffe1\011\uffe1\012" +
                          "\uffe1\014\uffe1\015\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1" +
                          "\022\uffe1\023\uffe1\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030" +
                          "\uffe1\031\uffe1\032\uffe1\036\uffe1\040\uffe1\041\uffe1\074\uffe1" +
                          "\001\002\000\062\005\uffe0\006\uffe0\007\uffe0\011\uffe0\012" +
                          "\uffe0\014\uffe0\015\uffe0\016\uffe0\017\uffe0\020\uffe0\021\uffe0" +
                          "\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\030" +
                          "\uffe0\031\uffe0\032\uffe0\036\uffe0\040\uffe0\041\uffe0\074\uffe0" +
                          "\001\002\000\056\005\uffe4\006\uffe4\007\uffe4\011\uffe4\012" +
                          "\uffe4\014\uffe4\015\uffe4\016\uffe4\017\067\020\064\023\071" +
                          "\024\072\025\070\026\065\027\066\030\074\031\063\032" +
                          "\uffe4\036\uffe4\040\uffe4\041\uffe4\074\uffe4\001\002\000\062" +
                          "\005\uffea\006\uffea\007\uffea\011\uffea\012\uffea\014\uffea\015" +
                          "\uffea\016\uffea\017\uffea\020\uffea\021\077\022\076\023\uffea" +
                          "\024\uffea\025\uffea\026\uffea\027\uffea\030\uffea\031\uffea\032" +
                          "\uffea\036\uffea\040\uffea\041\uffea\074\uffea\001\002\000\062" +
                          "\005\uffeb\006\uffeb\007\uffeb\011\uffeb\012\uffeb\014\uffeb\015" +
                          "\uffeb\016\uffeb\017\uffeb\020\uffeb\021\077\022\076\023\uffeb" +
                          "\024\uffeb\025\uffeb\026\uffeb\027\uffeb\030\uffeb\031\uffeb\032" +
                          "\uffeb\036\uffeb\040\uffeb\041\uffeb\074\uffeb\001\002\000\062" +
                          "\005\uffe9\006\uffe9\007\uffe9\011\uffe9\012\uffe9\014\uffe9\015" +
                          "\uffe9\016\uffe9\017\uffe9\020\uffe9\021\077\022\076\023\uffe9" +
                          "\024\uffe9\025\uffe9\026\uffe9\027\uffe9\030\uffe9\031\uffe9\032" +
                          "\uffe9\036\uffe9\040\uffe9\041\uffe9\074\uffe9\001\002\000\062" +
                          "\005\uffed\006\uffed\007\uffed\011\uffed\012\uffed\014\uffed\015" +
                          "\uffed\016\uffed\017\uffed\020\uffed\021\077\022\076\023\uffed" +
                          "\024\uffed\025\uffed\026\uffed\027\uffed\030\uffed\031\uffed\032" +
                          "\uffed\036\uffed\040\uffed\041\uffed\074\uffed\001\002\000\062" +
                          "\005\uffe7\006\uffe7\007\uffe7\011\uffe7\012\uffe7\014\uffe7\015" +
                          "\uffe7\016\uffe7\017\uffe7\020\uffe7\021\077\022\076\023\uffe7" +
                          "\024\uffe7\025\uffe7\026\uffe7\027\uffe7\030\uffe7\031\uffe7\032" +
                          "\uffe7\036\uffe7\040\uffe7\041\uffe7\074\uffe7\001\002\000\062" +
                          "\005\uffe8\006\uffe8\007\uffe8\011\uffe8\012\uffe8\014\uffe8\015" +
                          "\uffe8\016\uffe8\017\uffe8\020\uffe8\021\077\022\076\023\uffe8" +
                          "\024\uffe8\025\uffe8\026\uffe8\027\uffe8\030\uffe8\031\uffe8\032" +
                          "\uffe8\036\uffe8\040\uffe8\041\uffe8\074\uffe8\001\002\000\062" +
                          "\005\uffec\006\uffec\007\uffec\011\uffec\012\uffec\014\uffec\015" +
                          "\uffec\016\uffec\017\uffec\020\uffec\021\077\022\076\023\uffec" +
                          "\024\uffec\025\uffec\026\uffec\027\uffec\030\uffec\031\uffec\032" +
                          "\uffec\036\uffec\040\uffec\041\uffec\074\uffec\001\002\000\056" +
                          "\005\uffe5\006\uffe5\007\uffe5\011\uffe5\012\uffe5\014\uffe5\015" +
                          "\uffe5\016\uffe5\017\067\020\064\023\071\024\072\025\070" +
                          "\026\065\027\066\030\074\031\uffe5\032\uffe5\036\uffe5\040" +
                          "\uffe5\041\uffe5\074\uffe5\001\002\000\004\075\114\001\002" +
                          "\000\044\002\uffd5\042\uffd5\043\uffd5\044\uffd5\045\uffd5\046" +
                          "\uffd5\047\uffd5\050\uffd5\051\uffd5\052\uffd5\053\uffd5\054\uffd5" +
                          "\055\uffd5\056\uffd5\057\uffd5\060\uffd5\061\uffd5\001\002\000" +
                          "\014\033\061\035\052\074\056\075\053\076\051\001\002" +
                          "\000\030\017\067\020\064\023\071\024\072\025\070\026" +
                          "\065\027\066\030\074\031\063\032\073\041\117\001\002" +
                          "\000\014\033\061\035\052\074\056\075\053\076\051\001" +
                          "\002\000\030\017\067\020\064\023\071\024\072\025\070" +
                          "\026\065\027\066\030\074\031\063\032\073\040\uffc6\001" +
                          "\002\000\030\017\067\020\064\023\071\024\072\025\070" +
                          "\026\065\027\066\030\074\031\063\032\073\036\122\001" +
                          "\002\000\062\005\uffdb\006\uffdb\007\uffdb\011\uffdb\012\uffdb" +
                          "\014\uffdb\015\uffdb\016\uffdb\017\uffdb\020\uffdb\021\uffdb\022" +
                          "\uffdb\023\uffdb\024\uffdb\025\uffdb\026\uffdb\027\uffdb\030\uffdb" +
                          "\031\uffdb\032\uffdb\036\uffdb\040\uffdb\041\uffdb\074\uffdb\001" +
                          "\002\000\020\062\042\063\041\064\040\065\035\066\043" +
                          "\067\037\074\034\001\002\000\004\040\125\001\002\000" +
                          "\004\075\126\001\002\000\044\002\uffcf\042\uffcf\043\uffcf" +
                          "\044\uffcf\045\uffcf\046\uffcf\047\uffcf\050\uffcf\051\uffcf\052" +
                          "\uffcf\053\uffcf\054\uffcf\055\uffcf\056\uffcf\057\uffcf\060\uffcf" +
                          "\061\uffcf\001\002\000\014\033\061\035\052\074\056\075" +
                          "\053\076\051\001\002\000\004\040\131\001\002\000\004" +
                          "\075\132\001\002\000\044\002\uffd1\042\uffd1\043\uffd1\044" +
                          "\uffd1\045\uffd1\046\uffd1\047\uffd1\050\uffd1\051\uffd1\052\uffd1" +
                          "\053\uffd1\054\uffd1\055\uffd1\056\uffd1\057\uffd1\060\uffd1\061" +
                          "\uffd1\001\002\000\014\070\136\071\141\072\135\073\137" +
                          "\074\134\001\002\000\004\040\uffbe\001\002\000\004\040" +
                          "\uffbb\001\002\000\004\040\uffbd\001\002\000\004\040\uffba" +
                          "\001\002\000\004\040\142\001\002\000\004\040\uffbc\001" +
                          "\002\000\004\075\143\001\002\000\044\002\uffce\042\uffce" +
                          "\043\uffce\044\uffce\045\uffce\046\uffce\047\uffce\050\uffce\051" +
                          "\uffce\052\uffce\053\uffce\054\uffce\055\uffce\056\uffce\057\uffce" +
                          "\060\uffce\061\uffce\001\002\000\014\033\061\035\052\074" +
                          "\056\075\053\076\051\001\002\000\004\040\146\001\002" +
                          "\000\004\075\147\001\002\000\044\002\uffd6\042\uffd6\043" +
                          "\uffd6\044\uffd6\045\uffd6\046\uffd6\047\uffd6\050\uffd6\051\uffd6" +
                          "\052\uffd6\053\uffd6\054\uffd6\055\uffd6\056\uffd6\057\uffd6\060" +
                          "\uffd6\061\uffd6\001\002\000\014\033\061\035\052\074\056" +
                          "\075\053\076\051\001\002\000\030\017\067\020\064\023" +
                          "\071\024\072\025\070\026\065\027\066\030\074\031\063" +
                          "\032\073\040\152\001\002\000\004\075\153\001\002\000" +
                          "\044\002\uffc8\042\uffc8\043\uffc8\044\uffc8\045\uffc8\046\uffc8" +
                          "\047\uffc8\050\uffc8\051\uffc8\052\uffc8\053\uffc8\054\uffc8\055" +
                          "\uffc8\056\uffc8\057\uffc8\060\uffc8\061\uffc8\001\002\000\020" +
                          "\062\042\063\041\064\040\065\035\066\043\067\037\074" +
                          "\034\001\002\000\004\040\156\001\002\000\004\075\157" +
                          "\001\002\000\044\002\uffd4\042\uffd4\043\uffd4\044\uffd4\045" +
                          "\uffd4\046\uffd4\047\uffd4\050\uffd4\051\uffd4\052\uffd4\053\uffd4" +
                          "\054\uffd4\055\uffd4\056\uffd4\057\uffd4\060\uffd4\061\uffd4\001" +
                          "\002\000\014\033\061\035\052\074\056\075\053\076\051" +
                          "\001\002\000\004\040\162\001\002\000\004\075\163\001" +
                          "\002\000\044\002\uffd0\042\uffd0\043\uffd0\044\uffd0\045\uffd0" +
                          "\046\uffd0\047\uffd0\050\uffd0\051\uffd0\052\uffd0\053\uffd0\054" +
                          "\uffd0\055\uffd0\056\uffd0\057\uffd0\060\uffd0\061\uffd0\001\002" +
                          "\000\014\033\061\035\052\074\056\075\053\076\051\001" +
                          "\002\000\004\040\166\001\002\000\004\075\167\001\002" +
                          "\000\044\002\uffcb\042\uffcb\043\uffcb\044\uffcb\045\uffcb\046" +
                          "\uffcb\047\uffcb\050\uffcb\051\uffcb\052\uffcb\053\uffcb\054\uffcb" +
                          "\055\uffcb\056\uffcb\057\uffcb\060\uffcb\061\uffcb\001\002\000" +
                          "\014\033\061\035\052\074\056\075\053\076\051\001\002" +
                          "\000\030\017\067\020\064\023\071\024\072\025\070\026" +
                          "\065\027\066\030\074\031\063\032\073\040\172\001\002" +
                          "\000\004\075\173\001\002\000\044\002\uffcd\042\uffcd\043" +
                          "\uffcd\044\uffcd\045\uffcd\046\uffcd\047\uffcd\050\uffcd\051\uffcd" +
                          "\052\uffcd\053\uffcd\054\uffcd\055\uffcd\056\uffcd\057\uffcd\060" +
                          "\uffcd\061\uffcd\001\002\000\044\002\uffd9\042\uffd9\043\uffd9" +
                          "\044\uffd9\045\uffd9\046\uffd9\047\uffd9\050\uffd9\051\uffd9\052" +
                          "\uffd9\053\uffd9\054\uffd9\055\uffd9\056\uffd9\057\uffd9\060\uffd9" +
                          "\061\uffd9\001\002\000\014\070\136\071\141\072\135\073" +
                          "\137\074\134\001\002\000\004\040\177\001\002\000\004" +
                          "\075\200\001\002\000\044\002\uffc9\042\uffc9\043\uffc9\044" +
                          "\uffc9\045\uffc9\046\uffc9\047\uffc9\050\uffc9\051\uffc9\052\uffc9" +
                          "\053\uffc9\054\uffc9\055\uffc9\056\uffc9\057\uffc9\060\uffc9\061" +
                          "\uffc9\001\002\000\014\070\136\071\141\072\135\073\137" +
                          "\074\134\001\002\000\004\040\203\001\002\000\004\075" +
                          "\204\001\002\000\044\002\uffd3\042\uffd3\043\uffd3\044\uffd3" +
                          "\045\uffd3\046\uffd3\047\uffd3\050\uffd3\051\uffd3\052\uffd3\053" +
                          "\uffd3\054\uffd3\055\uffd3\056\uffd3\057\uffd3\060\uffd3\061\uffd3" +
                          "\001\002\000\014\033\061\035\052\074\056\075\053\076" +
                          "\051\001\002\000\004\040\207\001\002\000\004\075\210" +
                          "\001\002\000\044\002\uffcc\042\uffcc\043\uffcc\044\uffcc\045" +
                          "\uffcc\046\uffcc\047\uffcc\050\uffcc\051\uffcc\052\uffcc\053\uffcc" +
                          "\054\uffcc\055\uffcc\056\uffcc\057\uffcc\060\uffcc\061\uffcc\001" +
                          "\002\000\014\033\061\035\052\074\056\075\053\076\051" +
                          "\001\002\000\030\017\067\020\064\023\071\024\072\025" +
                          "\070\026\065\027\066\030\074\031\063\032\073\040\213" +
                          "\001\002\000\004\075\214\001\002\000\044\002\uffd2\042" +
                          "\uffd2\043\uffd2\044\uffd2\045\uffd2\046\uffd2\047\uffd2\050\uffd2" +
                          "\051\uffd2\052\uffd2\053\uffd2\054\uffd2\055\uffd2\056\uffd2\057" +
                          "\uffd2\060\uffd2\061\uffd2\001\002\000\004\002\000\001\002" +
                          "\000\020\005\261\006\223\007\232\012\231\015\217\016" +
                          "\224\074\227\001\002\000\006\074\257\077\260\001\002" +
                          "\000\024\005\ufff7\006\ufff7\007\ufff7\011\ufff7\012\ufff7\014" +
                          "\ufff7\015\ufff7\016\ufff7\074\ufff7\001\002\000\024\005\ufffc" +
                          "\006\ufffc\007\ufffc\011\ufffc\012\ufffc\014\ufffc\015\ufffc\016" +
                          "\ufffc\074\ufffc\001\002\000\024\005\ufffa\006\ufffa\007\ufffa" +
                          "\011\ufffa\012\ufffa\014\ufffa\015\ufffa\016\ufffa\074\ufffa\001" +
                          "\002\000\004\074\254\001\002\000\004\074\253\001\002" +
                          "\000\024\005\ufffb\006\ufffb\007\ufffb\011\ufffb\012\ufffb\014" +
                          "\ufffb\015\ufffb\016\ufffb\074\ufffb\001\002\000\024\005\ufff6" +
                          "\006\ufff6\007\ufff6\011\ufff6\012\ufff6\014\ufff6\015\ufff6\016" +
                          "\ufff6\074\ufff6\001\002\000\004\034\251\001\002\000\024" +
                          "\005\ufff8\006\ufff8\007\ufff8\011\ufff8\012\ufff8\014\ufff8\015" +
                          "\ufff8\016\ufff8\074\ufff8\001\002\000\004\035\243\001\002" +
                          "\000\004\035\234\001\002\000\024\005\ufff9\006\ufff9\007" +
                          "\ufff9\011\ufff9\012\ufff9\014\ufff9\015\ufff9\016\ufff9\074\ufff9" +
                          "\001\002\000\014\033\061\035\052\074\056\075\053\076" +
                          "\051\001\002\000\030\017\067\020\064\023\071\024\072" +
                          "\025\070\026\065\027\066\030\074\031\063\032\073\036" +
                          "\236\001\002\000\004\010\237\001\002\000\016\006\223" +
                          "\007\232\012\231\015\217\016\224\074\227\001\002\000" +
                          "\020\006\223\007\232\011\242\012\231\015\217\016\224" +
                          "\074\227\001\002\000\024\005\ufffd\006\ufffd\007\ufffd\011" +
                          "\ufffd\012\ufffd\014\ufffd\015\ufffd\016\ufffd\074\ufffd\001\002" +
                          "\000\024\005\uffef\006\uffef\007\uffef\011\uffef\012\uffef\014" +
                          "\uffef\015\uffef\016\uffef\074\uffef\001\002\000\014\033\061" +
                          "\035\052\074\056\075\053\076\051\001\002\000\030\017" +
                          "\067\020\064\023\071\024\072\025\070\026\065\027\066" +
                          "\030\074\031\063\032\073\036\245\001\002\000\004\013" +
                          "\246\001\002\000\016\006\223\007\232\012\231\015\217" +
                          "\016\224\074\227\001\002\000\020\006\223\007\232\012" +
                          "\231\014\250\015\217\016\224\074\227\001\002\000\024" +
                          "\005\uffee\006\uffee\007\uffee\011\uffee\012\uffee\014\uffee\015" +
                          "\uffee\016\uffee\074\uffee\001\002\000\014\033\061\035\052" +
                          "\074\056\075\053\076\051\001\002\000\050\005\ufff3\006" +
                          "\ufff3\007\ufff3\011\ufff3\012\ufff3\014\ufff3\015\ufff3\016\ufff3" +
                          "\017\067\020\064\023\071\024\072\025\070\026\065\027" +
                          "\066\030\074\031\063\032\073\074\ufff3\001\002\000\024" +
                          "\005\ufff0\006\ufff0\007\ufff0\011\ufff0\012\ufff0\014\ufff0\015" +
                          "\ufff0\016\ufff0\074\ufff0\001\002\000\026\005\ufff5\006\ufff5" +
                          "\007\ufff5\011\ufff5\012\ufff5\014\ufff5\015\ufff5\016\ufff5\034" +
                          "\255\074\ufff5\001\002\000\014\033\061\035\052\074\056" +
                          "\075\053\076\051\001\002\000\050\005\ufff4\006\ufff4\007" +
                          "\ufff4\011\ufff4\012\ufff4\014\ufff4\015\ufff4\016\ufff4\017\067" +
                          "\020\064\023\071\024\072\025\070\026\065\027\066\030" +
                          "\074\031\063\032\073\074\ufff4\001\002\000\024\005\ufff1" +
                          "\006\ufff1\007\ufff1\011\ufff1\012\ufff1\014\ufff1\015\ufff1\016" +
                          "\ufff1\074\ufff1\001\002\000\024\005\ufff2\006\ufff2\007\ufff2" +
                          "\011\ufff2\012\ufff2\014\ufff2\015\ufff2\016\ufff2\074\ufff2\001" +
                          "\002\000\006\002\ufffe\037\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table =
          unpackFromStrings(new String[] {
                  "\000\257\000\006\002\004\003\005\001\001\000\022\004" +
                          "\215\005\220\006\221\007\224\010\232\011\227\012\217" +
                          "\013\225\001\001\000\002\001\001\000\002\001\001\000" +
                          "\010\017\030\020\013\021\027\001\001\000\002\001\001" +
                          "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                          "\004\021\173\001\001\000\002\001\001\000\002\001\001" +
                          "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                          "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
                          "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                          "\001\000\002\001\001\000\002\001\001\000\004\022\035" +
                          "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                          "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                          "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                          "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
                          "\014\054\015\053\016\056\024\057\001\001\000\002\001" +
                          "\001\000\010\014\120\015\053\016\056\001\001\000\002" +
                          "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                          "\001\000\002\001\001\000\002\001\001\000\010\014\061" +
                          "\015\053\016\056\001\001\000\002\001\001\000\010\014" +
                          "\111\015\053\016\056\001\001\000\006\015\110\016\056" +
                          "\001\001\000\006\015\107\016\056\001\001\000\006\015" +
                          "\106\016\056\001\001\000\006\015\105\016\056\001\001" +
                          "\000\006\015\104\016\056\001\001\000\006\015\103\016" +
                          "\056\001\001\000\006\015\102\016\056\001\001\000\010" +
                          "\014\101\015\053\016\056\001\001\000\006\015\074\016" +
                          "\056\001\001\000\002\001\001\000\004\016\100\001\001" +
                          "\000\004\016\077\001\001\000\002\001\001\000\002\001" +
                          "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                          "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                          "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
                          "\001\001\000\002\001\001\000\010\014\115\015\053\016" +
                          "\056\001\001\000\002\001\001\000\010\014\117\015\053" +
                          "\016\056\001\001\000\002\001\001\000\002\001\001\000" +
                          "\002\001\001\000\004\022\123\001\001\000\002\001\001" +
                          "\000\002\001\001\000\002\001\001\000\012\014\054\015" +
                          "\053\016\056\024\127\001\001\000\002\001\001\000\002" +
                          "\001\001\000\002\001\001\000\004\023\137\001\001\000" +
                          "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
                          "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                          "\001\000\002\001\001\000\012\014\054\015\053\016\056" +
                          "\024\144\001\001\000\002\001\001\000\002\001\001\000" +
                          "\002\001\001\000\010\014\150\015\053\016\056\001\001" +
                          "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                          "\004\022\154\001\001\000\002\001\001\000\002\001\001" +
                          "\000\002\001\001\000\012\014\054\015\053\016\056\024" +
                          "\160\001\001\000\002\001\001\000\002\001\001\000\002" +
                          "\001\001\000\012\014\054\015\053\016\056\024\164\001" +
                          "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                          "\000\010\014\170\015\053\016\056\001\001\000\002\001" +
                          "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                          "\000\004\023\175\001\001\000\002\001\001\000\002\001" +
                          "\001\000\002\001\001\000\004\023\201\001\001\000\002" +
                          "\001\001\000\002\001\001\000\002\001\001\000\012\014" +
                          "\054\015\053\016\056\024\205\001\001\000\002\001\001" +
                          "\000\002\001\001\000\002\001\001\000\010\014\211\015" +
                          "\053\016\056\001\001\000\002\001\001\000\002\001\001" +
                          "\000\002\001\001\000\002\001\001\000\020\005\240\006" +
                          "\221\007\224\010\232\011\227\012\217\013\225\001\001" +
                          "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                          "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
                          "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
                          "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
                          "\000\010\014\234\015\053\016\056\001\001\000\002\001" +
                          "\001\000\002\001\001\000\022\004\237\005\220\006\221" +
                          "\007\224\010\232\011\227\012\217\013\225\001\001\000" +
                          "\020\005\240\006\221\007\224\010\232\011\227\012\217" +
                          "\013\225\001\001\000\002\001\001\000\002\001\001\000" +
                          "\010\014\243\015\053\016\056\001\001\000\002\001\001" +
                          "\000\002\001\001\000\022\004\246\005\220\006\221\007" +
                          "\224\010\232\011\227\012\217\013\225\001\001\000\020" +
                          "\005\240\006\221\007\224\010\232\011\227\012\217\013" +
                          "\225\001\001\000\002\001\001\000\010\014\251\015\053" +
                          "\016\056\001\001\000\002\001\001\000\002\001\001\000" +
                          "\002\001\001\000\010\014\255\015\053\016\056\001\001" +
                          "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
                          "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
  {
    action_obj = new CUP$parser$actions(this);
  }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
          int                        act_num,
          java_cup.runtime.lr_parser parser,
          java.util.Stack            stack,
          int                        top)
          throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  private java.util.List<String> syntaxErrors = new java.util.ArrayList<>();

  public java.util.List<String> getSyntaxErrors() {
    return syntaxErrors;
  }

  @Override
  public void report_error(String message, Object info) {
    if (info instanceof java_cup.runtime.Symbol) {
      java_cup.runtime.Symbol s = (java_cup.runtime.Symbol) info;
      String unexpected = (s.value != null) ? s.value.toString() : sym.terminalNames[s.sym];
      syntaxErrors.add(
              "Sintáctico -> Línea: " + s.left +
                      " Columna: " + s.right +
                      " Token inesperado: '" + unexpected + "'" +
                      " | Mensaje: " + message
      );
    } else {
      syntaxErrors.add("Sintáctico -> " + message);
    }
  }

  @Override
  public void report_fatal_error(String message, Object info) throws Exception {
    if (info instanceof java_cup.runtime.Symbol) {
      java_cup.runtime.Symbol s = (java_cup.runtime.Symbol) info;
      String unexpected = (s.value != null) ? s.value.toString() : sym.terminalNames[s.sym];
      syntaxErrors.add(
              "Fatal -> Línea: " + s.left +
                      " Columna: " + s.right +
                      " Token inesperado: '" + unexpected + "'" +
                      " | Mensaje: " + message
      );
    } else {
      syntaxErrors.add("Fatal -> " + message);
    }
    super.report_fatal_error(message, info);
  }


  /** Cup generated class to encapsulate user supplied action code.*/
  @SuppressWarnings({"rawtypes", "unchecked", "unused"})
  class CUP$parser$actions {
    private final parser parser;

    /** Constructor */
    CUP$parser$actions(parser parser) {
      this.parser = parser;
    }

    /** Method 0 with the actual generated action code for actions 0 to 300. */
    public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack            CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
      {
        /*. . . . . . . . . . . . . . . . . . . .*/
        case 0: // inicio ::= algoritmo SEPARADOR configuracion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 1: // $START ::= inicio EOF
        {
          Object RESULT =null;
          int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
          int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
          Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
          RESULT = start_val;
          CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        /* ACCEPT */
        CUP$parser$parser.done_parsing();
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 2: // inicio ::= algoritmo
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 3: // algoritmo ::= INICIO bloque FIN
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("algoritmo",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 4: // bloque ::= bloque instruccion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 5: // bloque ::= instruccion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 6: // instruccion ::= declaracion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 7: // instruccion ::= asignacion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 8: // instruccion ::= mostrar
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 9: // instruccion ::= leer
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 10: // instruccion ::= si
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 11: // instruccion ::= mientras
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 12: // declaracion ::= VAR ID
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 13: // declaracion ::= VAR ID ASIGNACION expresion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 14: // asignacion ::= ID ASIGNACION expresion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("asignacion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 15: // mostrar ::= MOSTRAR CADENA
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 16: // mostrar ::= MOSTRAR ID
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("mostrar",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 17: // leer ::= LEER ID
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("leer",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 18: // si ::= SI PAREN_IZQ expresion PAREN_DER ENTONCES bloque FINSI
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("si",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 19: // mientras ::= MIENTRAS PAREN_IZQ expresion PAREN_DER HACER bloque FINMIENTRAS
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("mientras",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 20: // expresion ::= expresion MAS termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 21: // expresion ::= expresion MENOS termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 22: // expresion ::= expresion IGUAL termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 23: // expresion ::= expresion DIFERENTE termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 24: // expresion ::= expresion MAYOR termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 25: // expresion ::= expresion MENOR termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 26: // expresion ::= expresion MAYOR_IGUAL termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 27: // expresion ::= expresion MENOR_IGUAL termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 28: // expresion ::= expresion AND expresion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 29: // expresion ::= expresion OR expresion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 30: // expresion ::= NOT expresion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 31: // expresion ::= termino
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 32: // termino ::= termino POR factor
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 33: // termino ::= termino DIV factor
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 34: // termino ::= factor
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 35: // factor ::= ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 36: // factor ::= DECIMAL
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 37: // factor ::= ID
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 38: // factor ::= PAREN_IZQ expresion PAREN_DER
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 39: // configuracion ::= lista_config
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("configuracion",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 40: // lista_config ::= lista_config config
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_config",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 41: // lista_config ::= config
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_config",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 42: // config ::= DEFAULT ASIGNACION ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 43: // config ::= COLOR_TEXTO_SI ASIGNACION color_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 44: // config ::= COLOR_SI ASIGNACION color_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 45: // config ::= FIGURA_SI ASIGNACION figura_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 46: // config ::= LETRA_SI ASIGNACION letra_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 47: // config ::= LETRA_SIZE_SI ASIGNACION expresion BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 48: // config ::= COLOR_TEXTO_MIENTRAS ASIGNACION color_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 49: // config ::= COLOR_MIENTRAS ASIGNACION color_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 50: // config ::= FIGURA_MIENTRAS ASIGNACION figura_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 51: // config ::= LETRA_MIENTRAS ASIGNACION letra_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 52: // config ::= LETRA_SIZE_MIENTRAS ASIGNACION expresion BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 53: // config ::= COLOR_TEXTO_BLOQUE ASIGNACION color_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 54: // config ::= COLOR_BLOQUE ASIGNACION color_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 55: // config ::= FIGURA_BLOQUE ASIGNACION figura_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 56: // config ::= LETRA_BLOQUE ASIGNACION letra_valor BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 57: // config ::= LETRA_SIZE_BLOQUE ASIGNACION expresion BARRA ENTERO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("config",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 58: // color_valor ::= expresion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("color_valor",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 59: // color_valor ::= expresion COMA expresion COMA expresion
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("color_valor",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 60: // figura_valor ::= ID
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("figura_valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 61: // figura_valor ::= ELIPSE
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("figura_valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 62: // figura_valor ::= CIRCULO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("figura_valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 63: // figura_valor ::= PARALELOGRAMO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("figura_valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 64: // figura_valor ::= RECTANGULO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("figura_valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 65: // figura_valor ::= ROMBO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("figura_valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 66: // figura_valor ::= RECTANGULO_REDONDEADO
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("figura_valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 67: // letra_valor ::= ID
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("letra_valor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 68: // letra_valor ::= ARIAL
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("letra_valor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 69: // letra_valor ::= TIMES_NEW_ROMAN
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("letra_valor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 70: // letra_valor ::= COMIC_SANS
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("letra_valor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /*. . . . . . . . . . . . . . . . . . . .*/
        case 71: // letra_valor ::= VERDANA
        {
          Object RESULT =null;

          CUP$parser$result = parser.getSymbolFactory().newSymbol("letra_valor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
        }
        return CUP$parser$result;

        /* . . . . . .*/
        default:
          throw new Exception(
                  "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

      }
    } /* end of method */

    /** Method splitting the generated action code into several parts. */
    public final java_cup.runtime.Symbol CUP$parser$do_action(
            int                        CUP$parser$act_num,
            java_cup.runtime.lr_parser CUP$parser$parser,
            java.util.Stack            CUP$parser$stack,
            int                        CUP$parser$top)
            throws java.lang.Exception
    {
      return CUP$parser$do_action_part00000000(
              CUP$parser$act_num,
              CUP$parser$parser,
              CUP$parser$stack,
              CUP$parser$top);
    }
  }

}
